"""add knowledge_node_enrichments table

Revision ID: 04f16bb65fa7
Revises: 653851246704
Create Date: 2026-04-12 01:16:43.874888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f16bb65fa7'
down_revision: Union[str, None] = '653851246704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_node_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_node_id', sa.Integer(), nullable=False, unique=True),
    sa.Column('learning_note', sa.Text(), nullable=True),
    sa.Column('memory_tip', sa.Text(), nullable=True),
    sa.Column('key_formula', sa.Text(), nullable=True),
    sa.Column('difficulty_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_node_enrichments_id'), 'knowledge_node_enrichments', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_node_enrichments_knowledge_node_id'), 'knowledge_node_enrichments', ['knowledge_node_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_node_enrichments_knowledge_node_id'), table_name='knowledge_node_enrichments')
    op.drop_index(op.f('ix_knowledge_node_enrichments_id'), table_name='knowledge_node_enrichments')
    op.drop_table('knowledge_node_enrichments')
    # ### end Alembic commands ###
