"""upgrade lesson db

Revision ID: 653851246704
Revises: e45e095002d1
Create Date: 2026-03-27 21:07:13.020651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653851246704'
down_revision: Union[str, None] = 'e45e095002d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('duration_mins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'duration_mins')
    # ### end Alembic commands ###
